/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera.Productos;
    
/**
 *
 * @author 192545681742
 */
public class GestionDeProductos extends javax.swing.JPanel {
    
    private AnadirProducto anadirP = new AnadirProducto();
    private QuitarProducto quitarP = new QuitarProducto();
    private AnadirExistencias anadirE = new AnadirExistencias();
    private QuitarExistencia quitarE = new QuitarExistencia();
    private EditarProducto editarP= new EditarProducto();
    private consulta2 consID= new consulta2();
    private consulta1 consCAT= new consulta1();
    
    /**
     * Creates new form GestionDeProductos
     */
    public GestionDeProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnadirE = new javax.swing.JButton();
        QuitarE = new javax.swing.JButton();
        AnadirP = new javax.swing.JButton();
        QuitarP = new javax.swing.JButton();
        EditarP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ConsulID = new javax.swing.JButton();
        ConsulCAT = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));

        AnadirE.setText("Añadir Existencias");
        AnadirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirEActionPerformed(evt);
            }
        });

        QuitarE.setText("Quitar Existencias");
        QuitarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarEActionPerformed(evt);
            }
        });

        AnadirP.setText("Añadir Producto");
        AnadirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirPActionPerformed(evt);
            }
        });

        QuitarP.setText("Quitar Producto");
        QuitarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarPActionPerformed(evt);
            }
        });

        EditarP.setText("Editar Producto");
        EditarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel1.setText("    GESTION DE PRODUCTOS");

        jPanel1.setLayout(new java.awt.BorderLayout());

        ConsulID.setText("Consulta-ID");
        ConsulID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulIDActionPerformed(evt);
            }
        });

        ConsulCAT.setText("Consulta- Categoría");
        ConsulCAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulCATActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ConsulCAT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ConsulID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AnadirE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AnadirP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(QuitarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(QuitarE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(AnadirP)
                        .addGap(18, 18, 18)
                        .addComponent(AnadirE)
                        .addGap(18, 18, 18)
                        .addComponent(QuitarP)
                        .addGap(18, 18, 18)
                        .addComponent(QuitarE)
                        .addGap(18, 18, 18)
                        .addComponent(EditarP)
                        .addGap(18, 18, 18)
                        .addComponent(ConsulID)
                        .addGap(18, 18, 18)
                        .addComponent(ConsulCAT)
                        .addGap(0, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void QuitarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarPActionPerformed
        jPanel1.setVisible(false);
        jPanel1.removeAll();
        jPanel1.add(quitarP);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_QuitarPActionPerformed

    private void AnadirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirEActionPerformed
        jPanel1.setVisible(false);
        jPanel1.removeAll();
        jPanel1.add(anadirE);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_AnadirEActionPerformed

    private void AnadirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirPActionPerformed
        jPanel1.setVisible(false);
        jPanel1.removeAll();
        jPanel1.add(anadirP);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_AnadirPActionPerformed

    private void EditarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPActionPerformed
        jPanel1.setVisible(false);
        jPanel1.removeAll();
        jPanel1.add(editarP);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_EditarPActionPerformed

    private void QuitarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarEActionPerformed
        jPanel1.setVisible(false);
        jPanel1.removeAll();
        jPanel1.add(quitarE);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_QuitarEActionPerformed

    private void ConsulIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulIDActionPerformed
        jPanel1.setVisible(false);
        jPanel1.removeAll();
        jPanel1.add(consID);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_ConsulIDActionPerformed

    private void ConsulCATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulCATActionPerformed
        jPanel1.setVisible(false);
        jPanel1.removeAll();
        jPanel1.add(consCAT);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_ConsulCATActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnadirE;
    private javax.swing.JButton AnadirP;
    private javax.swing.JButton ConsulCAT;
    private javax.swing.JButton ConsulID;
    private javax.swing.JButton EditarP;
    private javax.swing.JButton QuitarE;
    private javax.swing.JButton QuitarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
