/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera.Productos;

import Control.Verificaciones;
import Entidad.Producto;

/**
 *
 * @author 192545681742
 */
public class QuitarExistencia extends javax.swing.JPanel {

    /**
     * Creates new form QuitarExistencia
     */
    public QuitarExistencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        quitarExistencia = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idExistenciaEliminada = new javax.swing.JTextField();
        cantidadEliminada = new javax.swing.JTextField();
        resultado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel1.setText("QUITAR EXISTENCIA");

        quitarExistencia.setText("Quitar");
        quitarExistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarExistenciaActionPerformed(evt);
            }
        });

        jLabel2.setText("Identificación Producto");

        jLabel3.setText("Cantidad a quitar");

        resultado.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idExistenciaEliminada, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(quitarExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cantidadEliminada, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idExistenciaEliminada, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadEliminada, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(quitarExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void quitarExistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarExistenciaActionPerformed
        Verificaciones ver= new Verificaciones();
        String text= idExistenciaEliminada.getText();
        String text2= cantidadEliminada.getText();
        
        if(text.length()==0){
            resultado.setText("Es necesaria una ID válida para ésta operación");
        }else if(!ver.isNumeric(text)){
            resultado.setText("La ID debe ser un número");
        }else if(20<text.length()){
            resultado.setText("La ID no puede superar los 20 dígitos");
        }else if(!ver.VerificarExistenciaID(Integer.parseInt(text))){
            resultado.setText("No existe ningún producto registrado con ésta ID");
        }else{
            if(text2.length()==0){
                resultado.setText("No se ha agregado ninguna cantidad");
            }else if(!ver.isNumeric(text2)){
                resultado.setText("Ingrese un número como cantidad nueva");
            }else if(20<text2.length()){
                resultado.setText("El número de digitos no puede ser mayor a 20");
            }else if(Integer.parseInt(text2)<0){
                resultado.setText("La cantidad nueva de productos no puede ser negativa");
            }else{
                Producto producto= new Producto();
                    producto.setId(Integer.parseInt(text));
                    int a= ver.pdao.leerID(producto).getCantidad();
                    if(a>=Integer.parseInt(text2)){
                        int b=a-Integer.parseInt(text2);
                        ver.pdao.actualizarCANT(producto, b);
                        resultado.setText("Existencias eliminadas");
                    }
                    else{
                        resultado.setText("No hay suficientes existencias para ser eliminadas");
                    } 
            }
        }
    }//GEN-LAST:event_quitarExistenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidadEliminada;
    private javax.swing.JTextField idExistenciaEliminada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton quitarExistencia;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
